### PR TITLE
Update es.json

### PR DESCRIPTION
**Pull request by Wither362**
Just a little bit

### CODE REVIEW

**Review by Krymonota — APPROVED** [review]
Thanks!

**Comment by Wither362** [comment]
> Thanks!

No problem!

**Comment by Wither362** [comment]
Do I add me to the credits?

**Comment by Krymonota** [comment]
@Wither362
See [How can I contribute?](https://github.com/fnbrco/translations#how-can-i-contribute):
> In your pull request tell us your Discord name and discriminator and we will give you a Translator role on our Discord, make your [fnbr.co account](https://fnbr.co/oauth) have no adverts and credit you as a thank you.

So please let me know your Discord tag 🙂

**Comment by Wither362** [comment]
> @Wither362 See [How can I contribute?](https://github.com/fnbrco/translations#how-can-i-contribute):
> 
> > In your pull request tell us your Discord name and discriminator and we will give you a Translator role on our Discord, make your [fnbr.co account](https://fnbr.co/oauth) have no adverts and credit you as a thank you.
> 
> So please let me know your Discord tag 🙂

Wither#978, let me know if I can translate more things and I’ll do it

**Comment by Krymonota** [comment]
> Wither#978

I've never seen a three-digit discriminator/tag before 😅 Are you sure there's no 0 at the beginning or end, like Wither#0978 or Wither#9780? I'll add you to the credits after your response.

Currently there are no new strings that need to be translated into Spanish, but feel free to proofread the existing Spanish translations (and correct them if necessary) if you would like to do that 🙂

If you want to get the translator role and an ad-free experience on the website, you need to join the official fnbr.co Discord server: https://discord.gg/HFXPj6wPxc (I couldn't find you on the Discord server.)

**Comment by Krymonota** [comment]
For reference: https://github.com/fnbrco/translations/commit/86e4102c4d2c580084755ab564e31d9c16a654e3

**Pull request merged**
